version: '3'
services:
  php:
    user: ${CURRENT_UID}
    build: ./docker/php
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/myapp
    network_mode: "host"
  mail:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
