---
- name: TOOLS | fish + vim + git
  apt:
    name:
      - fish
      - vim
      - git
      - acl
    state: present
- name: VIM | autoload directory
  file: path=/etc/vim/autoload state=directory
- name: VIM | vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /etc/vim/autoload/plug.vim
- name: VIM | .vimrc
  get_url:
    url: https://raw.githubusercontent.com/Grafikart/dotfiles/master/config/vim/.vimrc
    dest: /etc/vim/vimrc.local
- name: VIM | .vimrc tweaks
  lineinfile:
    path: /etc/vim/vimrc.local
    regexp: '^call plug#begin'
    line: "call plug#begin('/etc/vim/plugged')"
- name: VIM | +PlugInstall
  command: vim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty
