---
symfony_shared_path:
  - var/log
symfony_shared_files:
  - .env
ansistrano_shared_paths: "{{ shared_paths }} + {{ symfony_shared_path }}"
ansistrano_shared_files: "{{ shared_files }} + {{ symfony_shared_files }}"
ansistrano_before_symlink_shared_tasks_file: "{{ playbook_dir }}/symfony/tasks/before_symlink.yml"
ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/symfony/tasks/end.yml"
ansistrano_deploy_to: "{{ path }}"
ansistrano_allow_anonymous_stats: false
ansistrano_keep_releases: "{{ releases }}"
ansistrano_deploy_via: git
ansistrano_git_repo: "{{ git }}"
